{
 "title": "NoInflux-Server_Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Process Disk Operation(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, indicatorvalue as value  from (\nselect [capture_time] ,\n servername+'-'+replace(indicatorname,'ps_disk_ops_','') as metric,\n  indicatorvalue\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \nunpivot\n(\n  indicatorvalue\n  for indicatorname in (\n  \n  ps_disk_ops_read\n  \n  ,ps_disk_ops_write\n  \n  )\n) unpiv\n)X\n\nWHERE\n  $__timeFilter(capture_time)\nORDER BY\n  capture_time ASC"
    }
   ]
  },
  {
   "title": "Processes CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "in Percentage(%)" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, indicatorvalue as value  from (\nselect [capture_time] ,servername+'-'+replace(indicatorname,'ps_cputime_','') as metric,\n  indicatorvalue\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \nunpivot\n(\n  indicatorvalue\n  for indicatorname in (\n  \n  ps_cputime_system\n  \n  ,ps_cputime_user\n  \n  )\n) unpiv\n)X\n\n\nWHERE\n  $__timeFilter(capture_time)\nORDER BY\n  capture_time ASC"
    }
   ]
  },
  {
   "title": "Process Count(in numbers)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "No. of process(s)" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, indicatorvalue as value  from (\nselect [capture_time] ,\n  servername+'-'+(case indicatorname when 'ps_count' then 'Server Process Count' else 'SQL Process Count' end) as metric,\n  indicatorvalue\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \nunpivot\n(\n  indicatorvalue\n  for indicatorname in (\n  ps_count\n  ,ps_count_sql\n  )\n) unpiv\n)X\n\nWHERE\n  $__timeFilter(capture_time)\nORDER BY\n  capture_time ASC"
    }
   ]
  },
  {
   "title": "Load Short Term(Load per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "in Seconds(s)" }
   ],
   "targets": [
    {
     "rawSql": "  select [capture_time] as time ,\n  servername+'-'+'Load Short Term' as metric,\n   Load_Short_term as value\n   from [MetricsCollector].[dbo].[SQLHardwareMetrics] \nWHERE\n  $__timeFilter(capture_time)\nORDER BY\n capture_time ASC"
    }
   ]
  },
  {
   "title": "Process Resident Size Set(In Memory)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decgbytes", "label": "in Gigabyte(s)" }
   ],
   "targets": [
    {
     "rawSql": "select  capture_time as time ,\nservername+'-'+'Process Resident Size' as metric,\nps_rss as value\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \nwhere ps_rss is not null and  $__timeFilter(capture_time)\n  order by capture_time "
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent", "label": "in Percentage(%)" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, 100-indicatorvalue as value  from (\nselect [capture_time] ,\n servername+'-'+ (case indicatorname \n  when 'Free_space_Host' then 'Host'\n else 'Host Boot'\n  \n     end) as metric,\n  indicatorvalue\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \nunpivot\n(\n  indicatorvalue\n  for indicatorname in (Free_space_Host, [Free_space_Host_boot])\n) unpiv\n)X\n\nWHERE\n  $__timeFilter(capture_time)\nORDER BY capture_time ASC"
    }
   ]
  },
  {
   "title": "Network Packets/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, ((indicatorvalue/8)/1500) as value  from (\nselect [capture_time] ,\n  servername+'-'+(case indicatorname \n  when 'Network_packets_eth0_rx' then 'eth0(rx)'\n  when 'Network_packets_eth0_tx' then 'eth0(tx)'\n  when 'Network_packets_eth1_rx' then 'eth1(rx)'\n  when 'Network_packets_eth1_tx' then 'eth1(tx)'\n  \n     end) as metric,\n  indicatorvalue\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \nunpivot\n(\n  indicatorvalue\n  for indicatorname in ([Network_packets_eth0_rx], [Network_packets_eth0_tx], [Network_packets_eth1_rx],[Network_packets_eth1_tx])\n) unpiv\n)X\n\n\nWHERE\n  $__timeFilter(capture_time)\nORDER BY\n  capture_time ASC"
    }
   ]
  },
  {
   "title": "Network Traffic/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, (indicatorvalue/(1024*1024)) as value  from (\r\nselect [capture_time] ,\r\n servername+'-'+ (case indicatorname \r\n  when 'Network_traffic_eth0_rx' then 'eth0(rx)'\r\n  when 'Network_traffic_eth0_tx' then 'eth0(tx)'\r\n  when 'Network_traffic_eth1_rx' then 'eth1(rx)'\r\n  when 'Network_traffic_eth1_tx' then 'eth1(tx)'\r\n  \r\n     end) as metric,\r\n  indicatorvalue\r\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \r\nunpivot\r\n(\r\n  indicatorvalue\r\n  for indicatorname in ([Network_traffic_eth0_rx], [Network_traffic_eth0_tx], [Network_traffic_eth1_rx],[Network_traffic_eth1_tx])\r\n) unpiv\r\n)X\r\n\r\nwhere $__timeFilter(Capture_Time)\r\norder by Capture_Time"
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "decgbytes", "label": "in Gigabyte(s)" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, indicatorvalue as value  from (\r\nselect [capture_time] ,\r\n  servername+'-'+replace(indicatorname,'Mem_','Server ') as metric,\r\n  indicatorvalue\r\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \r\nunpivot\r\n(\r\n  indicatorvalue\r\n  for indicatorname in (\r\n  [Mem_free]\r\n  ,[Mem_cached]\r\n  ,[Mem_Used]\r\n  )\r\n) unpiv\r\n)X\r\nwhere $__timeFilter(Capture_Time) order by capture_time"
    },
    {
     "rawSql": "select [capture_time]  as time,metric, indicatorvalue as value  from (\r\nselect [capture_time] ,\r\n  servername+'-'+replace(indicatorname,'SQL_Mem_','SQL ') as metric,\r\n  indicatorvalue\r\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \r\nunpivot\r\n(\r\n  indicatorvalue\r\n  for indicatorname in (\r\n  [SQL_Mem_Free]\r\n  ,[SQL_Mem_Cached]\r\n  ,[SQL_Mem_Used]\r\n  )\r\n) unpiv\r\n)X\r\nwhere $__timeFilter(Capture_Time) order by capture_time"
    }
   ]
  },
  {
   "title": "Uptime Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time] as time,\r\n  servername+'-'+'uptime' as metric,\r\n  uptime/(60*60*24) as value\r\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics]\r\nwhere $__timeFilter(Capture_Time) order by capture_time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "select [capture_time]  as time,metric, indicatorvalue as value  from (\r\nselect [capture_time] ,\r\n servername+'-'+ replace(indicatorname,'cpu_','') as metric,\r\n  indicatorvalue\r\nfrom [MetricsCollector].[dbo].[SQLHardwareMetrics] \r\nunpivot\r\n(\r\n  indicatorvalue\r\n  for indicatorname in ([cpu_idle], [cpu_interrup], [cpu_nice],[cpu_softirq],[cpu_steal],[cpu_system],[cpu_user],[cpu_wait])\r\n) unpiv\r\n)X\r\nwhere $__timeFilter(capture_time)\r\n\r\norder by capture_time\r\n"
    }
   ]
  }
 ]
}