{
 "title": "NoInflux-SQL Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory Broker Clerks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes", "label": "in Megabytes(MB)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  Capture_Time as time,\r\n  (coalesce([Data_Value],[Data_Value_PerSecond])*8)/1024 as value,\r\n  a.ServerName+'-'+b.Category_Variable as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=4 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY b.Category_Variable_ID ,capture_time"
    }
   ]
  },
  {
   "title": "Wait Statistics(wait_time_seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Per Second values" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  Capture_Time time,\r\n  [Data_Value_PerSecond] as valueOne,\r\n  a.ServerName+'-'+replace(b.Category_Variable,'_',' ') as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=7 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY b.Category_Variable_ID,Capture_Time"
    }
   ]
  },
  {
   "title": "Wait statistics( Cumulative Total Counts)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    {
     "format": "none",
     "label": "Cumulative count since service started"
    }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  Capture_Time time,\r\n  [Data_Value] as valueOne,\r\n  a.ServerName+'-'+replace(b.Category_Variable,'_',' ') as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=7 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY b.Category_Variable_ID,Capture_Time"
    }
   ]
  },
  {
   "title": "SQL Server Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "Per second" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n Capture_Time time,\r\n  coalesce([Data_Value],[Data_Value_PerSecond]) as valueOne,\r\n  a.ServerName+'-'+b.Category_Variable as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=6 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY b.Category_Variable_ID,Capture_Time"
    }
   ]
  },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "Per Sercond value" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  Capture_Time time,\r\n  coalesce([Data_Value],[Data_Value_PerSecond]) as value,\r\n  a.ServerName+'-'+b.Category_Variable as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=5 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY b.Category_Variable_ID,Capture_Time"
    }
   ]
  },
  {
   "title": "DataBase Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "In Seconds(Sec)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  Capture_Time time,\r\n  coalesce([Data_Value],[Data_Value_PerSecond]) as valueOne,\r\n  a.ServerName+'-'+b.Category_Variable as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=3 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY b.Category_Variable_ID,Capture_Time"
    }
   ]
  },
  {
   "title": "Buffer cache Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none", "label": "In seconds(sec)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  Capture_Time as time,\r\n  coalesce([Data_Value],[Data_Value_PerSecond]) as valueOne,\r\n  a.ServerName+'-'+b.Category_Variable as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=2 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY b.Category_Variable_ID,Capture_Time"
    }
   ]
  },
  {
   "title": "Always On",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none", "label": "As per second basis" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  Capture_Time as time,\r\n  coalesce([Data_Value],[Data_Value_PerSecond]) as valueOne,\r\n  a.ServerName+'-'+b.Category_Variable as metric\r\nFROM\r\n  [metricscollector].[dbo].[SQL_Server_Metrics] a inner join [metricscollector].dbo.SQL_Metrics_Name b on a.Metric_ID=b.Category_Variable_ID and a.Graph_ID=b.Graph_ID\r\nWHERE  b.Graph_ID=1 and\r\n  $__timeFilter(Capture_Time)\r\nORDER BY Capture_Time"
    }
   ]
  }
 ]
}